config/routes.rb
Rails.application.routes.draw do

  resources :answers
  resources :questions, except: [:destroy]
  resources :users
  resources :sessions, only: [:new,:create]

  root 'home#index'

  get  '/sessions/new' => 'sessions#new'
  get 'questions/:id/destroy' => 'questions#destroy', as: :destroy_question
  get '/home' => 'home#index'

  get '/logout' => 'sessions#destroy', as: :logout

end

app/models/answer.rb
class Answer < ActiveRecord::Base
      belongs_to :question
      belongs_to :user
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
  belongs_to :user

  def gravatar




  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :answers


  has_secure_password
  validates :username, presence: true


end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create


    question = Question.find(params[:answer][:question_id])
    question.answers.create(answer_params)
    redirect_to question

  end




private

def answer_params

  params.require(:answer).permit(:title,:body)

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :authorize  #makes them globally accessible

  def current_user
   return @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user #this is current_user the method
  end

  def authorize
    redirect_to root_path unless logged_in?
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
@questions = Question.all
  end


def temp

  redirect_to root_path

end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

before_action :authorize, only: [:edit]

def index
  @questions = Question.all

end



def show
@question = Question.find(params[:id])

end

def create
Question.create(question_params)


redirect_to root_path

  end

  def edit
@question = Question.find(params[:id])

  end

  def update

    @question = Question.find(params[:id])
    if @question.update_attributes(question_params)
      redirect_to root_path @question
    end
  end


  def destroy
@question = Question.find(params[:id])
if @question.destroy
  redirect_to root_path
  end
end




  private

  def question_params

    params.require(:question).permit(:title,:body)



  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by({username: params[:username]})
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:success] = "You now have admin privelages"
      redirect_to root_path
    else
      flash[:failure] = "Invalid password"
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

   before_action :authorize, only: [:show]

  def index
    @users = User.all
  end

  def show
  @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
    redirect_to root_path
    end
  end

  def edit
  end

  def update
  end

  def destroy

  end


  private
  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_nav_bar.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">



    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="css/bootstrap.min.css" type="text/css">

    <!-- Custom Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="font-awesome/css/font-awesome.min.css" type="text/css">

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="css/animate.min.css" type="text/css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="css/creative.css" type="text/css">

</head>



    <!-- Navigation -->
   <nav class="navbar navbar-default navbar-fixed-top">
       <div class="container">
           <!-- Brand and toggle get grouped for better mobile display -->
           <div class="navbar-header page-scroll">
               <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                   <span class="sr-only">Toggle navigation</span>
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
               </button>
               <a class="navbar-brand">Ask.io</a>
           </div>

           <!-- Collect the nav links, forms, and other content for toggling -->
           <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
               <ul class="nav navbar-nav navbar-right">
                   <li class="hidden">
                       <a href="#page-top"></a>
                   </li>
                   <li class="page-scroll">
                       <a href="/home">Home</a>
                   </li>
                   <li class="page-scroll">
                       <a class="page-scroll" href="" class="btn btn-success navbar-btn btn-sm" data-toggle= "modal" data-target= '#new-question-modal'>Ask Question</a></form></li>
                   </li>
                   <li class="page-scroll">
                     <% if logged_in? %>
                       <a class="page-scroll" href="<%= logout_path %>" class="">Admin Logout</a></form></li>
                     <% else %>

                       <!-- <a class="page-scroll" href="<%= new_session_path %>" class=""></a></form></li> -->
                     <% end %>
                   </li>
               </ul>
           </div>
           <!-- /.navbar-collapse -->
       </div>
       <!-- /.container-fluid -->
   </nav>


   <!-- Header -->
   <header>
       <div class="container">
           <div class="row">
               <div class="col-lg-12">
                   <img class="img-responsive" src="" alt="">
                   <div class="intro-text">
                       <span class="name">Hidden :)</span>
                       <hr class="star-light">
                       <span class="skills">Ever wonder what everyone has to say?</span>
                   </div>
               </div>
           </div>
       </div>
   </header>

   <!-- Portfolio Grid Section -->
   <section id="title">
       <div class="container">
           <div class="row">
               <div class="col-lg-12 text-center">
                   <h2>Ask.io</h2>
                   <hr class="star-primary">
               </div>
           </div>

app/views/home/_new_answer_form.html.erb
<div class="modal fade" id="new-answer-modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">New Answer</h4>
      </div>

      <%= form_for :answer, url: '/answers', html: {class: 'form-horizontal'} do  %>
        <input type ='hidden' name='answer[question_id]' value= "<%= @question.id %>" />
        <div class="modal-body">
          <div class="form-group">
            <label for="inputTitle" class="col-sm-2 control-label">Title</label>
            <div class="col-sm-10">
              <input type="title" name= 'answer[title]' class="form-control" id="inputTitle" placeholder="Your Title" required>

            </div>
          </div>
          <div class="form-group">
            <label for="inputQuestion" class="col-sm-2 control-label">Answer</label>
            <div class="col-sm-10">
              <input class="form-control" name ='answer[body]' id="inputAnswer" placeholder="Your answer" required> </textarea>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/_new_question_form.html.erb
<div class="modal fade" id="new-question-modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">New Question</h4>
      </div>

      <%= form_for :question, url: '/questions', html: {class: 'form-horizontal'} do  %>
        <div class="modal-body">
          <div class="form-group">
            <label for="inputEmail" class="col-sm-2 control-label">Title</label>
            <div class="col-sm-10">
              <input type="title" class="form-control" name='question[title]' id="inputTitle" placeholder="Subject" required>
            </div>
          </div>
          <div class="form-group">
            <label for="inputQuestion" class="col-sm-2 control-label">Question</label>
            <div class="col-sm-10">
              <input class="form-control" name ='question[body]' id="inputQuestion" placeholder="What would you like to ask?" required> </textarea>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<hr>
<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">


    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>



</head>

<body>
        <!-- /.container -->
    </nav>

    <header class="intro-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>What's on your mind?</h1>
                        <hr class="small">
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                      <div class = 'container'>
                        <% @questions.each do |q| %>
                          <div class="media">
                            <div class="media-left">
                          <a href="">
                            <img class="media-object" src="https://unsplash.it/80/80/?random" alt="...">
                          </a>
                        </div>
                        <div class="media-body">
                          <h4 class="media-heading">Title: <%= q.title %></h4>
                          <div><%= time_ago_in_words q.created_at %> ago </div>
                        <div> Question: <%= q.body %></div>
                          <div>
                            <a href = '<%= question_path(q) %>' class = "btn btn-success btn-xs">View Answers</a>
                      </div>
                      </div>

                      <%end%>
                <hr>
                <hr>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ask.us</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>



  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src= 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js'></script>

  <%= csrf_meta_tags %>

</head>

<body>




<%=render 'home/nav_bar'%>
  <div class = 'container'>
<%= yield %>


<!-- Footer -->
<footer>
    <div class="container text-center">
        <p>  &copy; 2016</p>
    </div>
</footer>

</div>

<%= render 'home/new_question_form' %>

</body>
</html>

app/views/questions/edit.html.erb
<h1> Edit Post </h1>



<div class = 'container'>
  <div class = "lead well">
    <div class="media">
      <div class="media-left">
    <a href="#">
      <img class="media-object" src="https://unsplash.it/80/80/?random" alt="...">
    </a>
  </div>
  <div class="media-body">
    <%= form_for @question do |f| %>
    <h4 class="media-heading">
     Title: <%= f.text_field :title%><br> </h4>
     Body: <%= f.text_area  :body%><br>
     <%= f.submit %>
</div>
</div>
</div>
</div>
<% end %>

<div class = "row">

  <div>

<div>
  <button type = "button" class = "btn btn-success btn-sm" data-toggle='modal' da ta-target=#new-answer-modal>Submit New Answer</a>
  </div>
<hr>


<div>
  <button type = "button" class = "btn btn-danger btn-sm" ><%= link_to 'Delete Question', destroy_question_path %></a>

</div>

</div>







<% @question.answers.each do |answer|  %>
<div class="media">
  <div class="media-left">
<a href="#">
  <img class="media-object" src="https://unsplash.it/80/80/?random" alt="...">
</a>
</div>
<div class="media-body">
<h4 class="media-heading">A:<%=answer.title %></h4>
<%= answer.body %>
</div>
</div>

<% end %>

</div>
</div>
</div>




<%= render 'home/new_answer_form' %>

app/views/questions/show.html.erb
<div class = 'container'>
  <div class = "lead well">
    <div class="media">
      <div class="media-left">
    <a href="#">
      <img class="media-object" src="https://unsplash.it/80/80/?random" alt="...">
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading"> <%=@question.title%> </h4>

    <%= @question.body %>
</div>
</div>
</div>
</div>


<div class = "row">

  <div>

<div>
  <button type = "button" class = "btn btn-success btn-sm" data-toggle='modal' data-target=#new-answer-modal>Submit New Answer</a>
  </div>
<hr>

<button type = "button" class = "btn btn-danger btn-sm" ><%= link_to 'Edit (Admin Only)', edit_question_path %>

</div>










<% @question.answers.each do |answer|  %>
<div class="media">
  <div class="media-left">
<a href="#">
  <img class="media-object" src="https://unsplash.it/80/80/?random" alt="...">
</a>
</div>
<div class="media-body">
<h4 class="media-heading">A: <%=answer.title %></h4>
<div><%= time_ago_in_words answer.created_at %> ago </div>
<%= answer.body %>
</div>
</div>

<% end %>

</div>
</div>
</div>






<%= render 'home/new_answer_form' %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

  <% @users.each do |u| %>
      <h3>  <%= u.username  %></h3>
  <% end %>

app/views/users/new.html.erb
<h1>Add a User</h1>
  <%= form_for @user do |u| %>
  name: <%= u.text_field :username %><br><br>
  password: <%= u.password_field :password %><br><br>
    <%= u.submit %>
    <% end %>